spring:

  # H2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kelly_cicd;MODE=MYSQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  # MySQL
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  config: classpath:logback-local.xml
  level:
    study:
      kellycicd: trace
